---
ansible_host: 192.168.56.102
#ansible_host: 192.168.56.106
#ansible_host: 192.168.56.103
ansible_user: root
ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
#ansible_ssh_private_key_file: ~/.ssh/deb1_rsa
docker_app_port: 5001
docker_name: web_app_1
